/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ghgj;

/**
 *
 * @author nasuu
 */
public class deposit extends javax.swing.JFrame {

    /**
     * Creates new form deposit
     */
    public deposit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dep = new javax.swing.JLabel();
        depositTF = new javax.swing.JTextField();
        ENTER = new javax.swing.JButton();
        depositBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dep.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        dep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dep.setText("DEPOSIT");
        getContentPane().add(dep, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 230, 30));

        depositTF.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        depositTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        depositTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositTFActionPerformed(evt);
            }
        });
        getContentPane().add(depositTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 290, 40));

        ENTER.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ENTER.setText("ENTER");
        ENTER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ENTERActionPerformed(evt);
            }
        });
        getContentPane().add(ENTER, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        depositBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/second.gif"))); // NOI18N
        depositBG.setText("jLabel1");
        getContentPane().add(depositBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void depositTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositTFActionPerformed

    }//GEN-LAST:event_depositTFActionPerformed

    private void ENTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ENTERActionPerformed
        AtmThird jf3 = new AtmThird();
        double deposit = Double.parseDouble(depositTF.getText());
        
        jf3.Realbalance = jf3.Realbalance + deposit;
        jf3.balanceLB.setText("BALANCE : " + Double.toString(jf3.Realbalance));
        jf3.show();
        dispose();
    }//GEN-LAST:event_ENTERActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deposit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ENTER;
    private javax.swing.JLabel dep;
    private javax.swing.JLabel depositBG;
    private javax.swing.JTextField depositTF;
    // End of variables declaration//GEN-END:variables
}
